### ISSUE TITLE
Set starting features and roadmap

### ISSUE THREAD

**Issue by fjaguero** [mozillahispano/sleep-webapp#1]
We need a roadmap **to start creating the issues and assigning them**.

It will be a good idea to have a launch meeting but I think that having an etherpad is great to work async.

We can discuss the initial roadmap here but I want to propose to have the documentation in this [etherpad](https://etherpad.mozilla.org/dHb1ZcKTgM).

I will be pushing this to get everyone on the same page and start ASAP.

**Comment by sebasmagri** [comment]
@fjaguero can we put the original webapps etherpad link in the description to have it handy?

**Comment by iampbernardo** [comment]
Sure. That one was the etherpad where we described some details
https://etherpad.mozilla.org/dHb1ZcKTgM

**Comment by iampbernardo** [comment]
I am sending some emails, and etherpad links tomorrow to coordinate the roadmap @fjaguero .

**Comment by fjaguero** [comment]
Great! :clap:

**Comment by fjaguero** [comment]
The thing is that we should move the roadmaps to english so everyone can understand/participate.

**Comment by iampbernardo** [comment]
Yes, don't worry. I linked that one because @sebasmagri asked for it.
The Etherpads of the project should be in english, acording to those issues.

**Comment by fjaguero** [comment]
Awesome :smile:

**Comment by fjaguero** [comment]
Since we have other priorities right now, I'm closing this.
